var shuffleSequence = seq("intro", sepWith("sep",  seq("practice")), "practiceover", sepWith("sep", rshuffle(startsWith("it"), startsWith("f"))));

var continueMessage = ["Klikni zde"];

var aj = "AcceptabilityJudgment";

var q = "Question";

var completionMessage = "[Děkuji Vám za účast. Odpovědi byly odeslány.]";

var ms = "Message";

var defaults = [    
    "Separator", { transfer: 800,
                   normalMessage: "Další položka se načítá.",
                   errorMessage: "Špatně. Počkejte prosím na další položku v experimentu." 
		 },
    "AcceptabilityJudgment", { as: ["1", "2", "3", "4", "5"],
                               presentAsScale: true,
                               leftComment: "(nepřijatelná věta)", rightComment: "(věta je v pořádku)" },
    "Message", { hideProgressBar: true, transfer: "click" }
];

 var progressBarText = "";

var items = [ ["sep", "Separator", { }],
 
	      ["intro", "Form", {continueMessage: "Pro vstup do experimentu klikněte zde.", html: { include: "example_intro.html" }}],

	      ["practice", aj, {s: {html: "<p><b>Nacházíte se v přípravné fázi experimentu. Přečtěte si kontext (text napsaný kurzívou) a testovací větu (není napsána kurzívou). Poté ohodnoťte testovací větu za předpokladu, že platí kontext. </p></b><p><i>Kontext: Mirek má několik líných zaměstnanců. Tvrdí o nich: </i></p><p>Tři zaměstnanci letos dostanou žádné prémie.</p><p><b>Výše uvedená věta odpovídá kontextu, ale nejspíše máte pocit, že věta neodpovídá zásadám českého jazyka. Vhodné číslo pro ohodnocení takové věty tudíž bude nejspíše 1. Klikněte na požadované číslo na škále..</b></p>"}}],
["practice", aj, {s: {html: "<p><b>Nacházíte se v přípravné fázi experimentu. Přečtěte si kontext (text napsaný kurzívou) a testovací větu (není napsána kurzívou). Poté ohodnoťte testovací větu za předpokladu, že platí kontext. </p></b><p><i>Kontext: Mirkovi se na zahradě porouchala hadice. Mirek říká opraváři do telefonu:</i></p><p>Tři zahradnice chtěly zalít květinové záhony, ale nemohly.</p><p><b>Výše uvedená věta neobsahuje žádnou nesrovnalost a vypadá zcela v pořádku. Toto je tedy příklad přijatelné věty, které odpovídá vyšší hodnocení – nejspíše 5. Klikněte na požadované číslo na škále.</b></p>"}}],
["practice", aj, {s: {html: "<p><b>Nacházíte se v přípravné fázi experimentu. Přečtěte si kontext (text napsaný kurzívou) a testovací větu (není napsána kurzívou). Poté ohodnoťte testovací větu za předpokladu, že platí kontext. </p></b><p><i>Kontext: Mirek potkal na obědě zahradníka Pepu. Mirek o něm říká:</i></p><p>Po příchodu ze záhonu měl Jirka na podrážce tři hlíny.</p><p><b> Tato věta není v pořádku: „tři hlíny“ se v češtině obvykle neříká, a navíc věta nesedí do kontextu, kde není zmíněn Jirka, nýbrž Pepa. Pokud souhlasíte, vyberte jedno z nižších čísel (nejspíš 1).</b></p>"}}],

	      ["practiceover", "Message", {continueMessage: "Klikněte zde pro pokračování experimentu", html: ["div", ["p", "Zde končí přípravná část experimentu. Klikněte níže pro vstup do samotného experimentu."]]}],

[["it1-pl-g-nopsi", 1], aj, {s:{html: "<p><i>Kontext: Jarda se zajímá o koně, což jsou obvykle energická zvířata. Tvrdí o nich:</i></p> Koně s velkou měrou energie běhají velkou vzdálenost."}}],
[["it1-pl-e-nopsi", 1], aj, {s:{html: "<p><i>Kontext: Jarda pozoroval koně, z nichž někteří utekli do města. Tvrdí o nich:</i></p> Koně s velkou měrou energie  běhají velkou vzdálenost."}}],
[["it1-s-g-nopsi", 1], aj, {s: {html: "<p><i>Kontext: Jarda se zajímá o koně, což jsou obvykle energická zvířata. Tvrdí o nich:</i></p>Kůň s velkou měrou energie běhá velkou vzdálenost."}}],
[["it1-s-e-nopsi", 1], aj, {s:{html: "<p><i>Kontext: Jarda pozoroval koně, z nichž někteří utekli do města. Tvrdí o nich:</i></p> Kůň s velkou měrou energie běhá velkou vzdálenost."}}],
[["it1-pl-g-psi", 1], aj, {s:{html: "<p><i>Kontext: Jarda se zajímá o koně, což jsou obvykle energická zvířata. Tvrdí o nich:</i></p> Koně se sebemenší trochou energie běhají velkou vzdálenost."}}],
[["it1-pl-e-psi", 1], aj, {s:{html: "<p><i>Kontext: Jarda pozoroval koně, z nichž někteří utekli do města. Tvrdí o nich:</i></p> Koně se sebemenší trochou energie  běhají velkou vzdálenost."}}],
[["it1-s-g-psi", 1], aj, {s: {html: "<p><i>Kontext: Jarda se zajímá o koně, což jsou obvykle energická zvířata. Tvrdí o nich:</i></p>Kůň se sebemenší trochou energie běhá velkou vzdálenost."}}],
[["it1-s-e-psi", 1], aj, {s:{html: "<p><i>Kontext: Jarda pozoroval koně, z nichž někteří utekli do města. Tvrdí o nich:</i></p> Kůň se sebemenší trochou energie běhá velkou vzdálenost."}}],
	     
[["it2-pl-g-nopsi", 2], aj, {s:{html: "<p><i>Kontext: Jarka se zajímá o zvířata, což jsou obvykle citliví tvorové. Tvrdí o nich:</i></p> Zvířata s velkou měrou vnímavosti slyší velký rámus."}}],
[["it2-pl-e-nopsi", 2], aj, {s: {html: "<p><i>Kontext: Jarka zkoumala zvířata, z nichž některá projevila strach z petard. Tvrdí o nich:</i></p> Zvířata s velkou měrou vnímavosti slyší velký rámus."}}],
[["it2-s-g-nopsi", 2], aj, {s: {html: "<p><i>Kontext: Jarka se zajímá o zvířata, což jsou obvykle citliví tvorové. Tvrdí o nich:</i></p> Zvíře s velkou měrou vnímavosti slyší velký rámus."}}],
[["it2-s-e-nopsi", 2], aj, {s: {html: "<p><i>Kontext: Jarka zkoumala zvířata, z nichž některá projevila strach z petard. Tvrdí o nich:</i></p> Zvíře s velkou měrou vnímavosti slyší velký rámus."}}],
[["it2-pl-g-psi", 2], aj, {s:{html: "<p><i>Kontext: Jarka se zajímá o zvířata, což jsou obvykle citliví tvorové. Tvrdí o nich:</i></p> Zvířata se sebemenší trochou vnímavosti slyší velký rámus."}}],
[["it2-pl-e-psi", 2], aj, {s: {html: "<p><i>Kontext: Jarka zkoumala zvířata, z nichž některá projevila strach z petard. Tvrdí o nich:</i></p> Zvířata se sebemenší trochou vnímavosti slyší velký rámus."}}],
[["it2-s-g-psi", 2], aj, {s: {html: "<p><i>Kontext: Jarka se zajímá o zvířata, což jsou obvykle citliví tvorové. Tvrdí o nich:</i></p> Zvíře se sebemenší trochou vnímavosti slyší velký rámus."}}],
[["it2-s-e-psi", 2], aj, {s: {html: "<p><i>Kontext: Jarka zkoumala zvířata, z nichž některá projevila strach z petard. Tvrdí o nich:</i></p> Zvíře se sebemenší trochou vnímavosti slyší velký rámus."}}],
	     
[["it3-pl-g-nopsi", 3], aj, {s: {html: "<p><i>Kontext: Zdeněk se zajímá o muslimy, což jsou obvykle zbožní lidé. Tvrdí o nich:</i></p> Muslimové s velkou silou víry chodí tradiční pouť."}}],
[["it3-pl-e-nopsi", 3], aj, {s: {html: "<p><i>Kontext: Zdeněk vyzpovídal muslimy, z nichž někteří poznali město Mekku. Tvrdí o nich:</i></p> Muslimové s velkou silou víry chodí tradiční pouť."}}],
[["it3-s-g-nopsi", 3], aj, {s: {html: "<p><i>Kontext: Zdeněk se zajímá o muslimy, což jsou obvykle zbožní lidé. Tvrdí o nich:</i></p> Muslim s velkou silou víry chodí tradiční pouť."}}],
[["it3-s-e-nopsi", 3], aj, {s:  {html: "<p><i>Kontext: Zdeněk vyzpovídal muslimy, z nichž někteří poznali město Mekku. Tvrdí o nich:</i></p> Muslim s dostatečnou silou víry chodí tradiční pouť."}}],
[["it3-pl-g-psi", 3], aj, {s: {html: "<p><i>Kontext: Zdeněk se zajímá o muslimy, což jsou obvykle zbožní lidé. Tvrdí o nich:</i></p> Muslimové se sebemenší stopou víry chodí tradiční pouť."}}],
[["it3-pl-e-psi", 3], aj, {s: {html: "<p><i>Kontext: Zdeněk vyzpovídal muslimy, z nichž někteří poznali město Mekku. Tvrdí o nich:</i></p> Muslimové se sebemenší stopou víry chodí tradiční pouť."}}],
[["it3-s-g-psi", 3], aj, {s: {html: "<p><i>Kontext: Zdeněk se zajímá o muslimy, což jsou obvykle zbožní lidé. Tvrdí o nich:</i></p> Muslim se sebemenší stopou víry chodí tradiční pouť."}}],
[["it3-s-e-psi", 3], aj, {s:  {html: "<p><i>Kontext: Zdeněk vyzpovídal muslimy, z nichž někteří poznali město Mekku. Tvrdí o nich:</i></p> Muslim se sebemenší stopou víry chodí tradiční pouť."}}],

[["it4-pl-g-nopsi", 4], aj, {s: {html: "<p><i>Kontext: Magda se zajímá o autory, což jsou obvykle namyšlení lidé. Tvrdí o nich:</i></p> Autoři s velkou měrou arogance píší naprostý brak."}}],
[["it4-pl-e-nopsi", 4], aj, {s: {html: "<p><i>Kontext: Magda sledovala autory, z nichž někteří odeslali nekvalitní texty. Tvrdí o nich:</i></p> Autoři s velkou měrou arogance píší naprostý brak."}}],
[["it4-s-g-nopsi", 4], aj, {s: {html: "<p><i>Kontext: Magda se zajímá o autory, což jsou obvykle namyšlení lidé. Tvrdí o nich:</i></p> Autor s velkou měrou arogance píše naprostý brak."}}],
[["it4-s-e-nopsi", 4], aj, {s: {html: "<p><i>Kontext: Magda sledovala autory, z nichž někteří odeslali nekvalitní texty. Tvrdí o nich:</i></p> Autor s velkou měrou arogance píše naprostý brak."}}],
[["it4-pl-g-psi", 4], aj, {s: {html: "<p><i>Kontext: Magda se zajímá o autory, což jsou obvykle namyšlení lidé. Tvrdí o nich:</i></p> Autoři se sebemenší známkou arogance píší naprostý brak."}}],
[["it4-pl-e-psi", 4], aj, {s: {html: "<p><i>Kontext: Magda sledovala autory, z nichž někteří odeslali nekvalitní texty. Tvrdí o nich:</i></p> Autoři se sebemenší známkou arogance píší naprostý brak."}}],
[["it4-s-g-psi", 4], aj, {s: {html: "<p><i>Kontext: Magda se zajímá o autory, což jsou obvykle namyšlení lidé. Tvrdí o nich:</i></p> Autor se sebemenší známkou arogance píše naprostý brak."}}],
[["it4-s-e-psi", 4], aj, {s: {html: "<p><i>Kontext: Magda sledovala autory, z nichž někteří odeslali nekvalitní texty. Tvrdí o nich:</i></p> Autor se sebemenší známkou arogance píše naprostý brak."}}],
	     
[["it5-pl-g-nopsi", 5], aj, {s: {html: "<p><i>Kontext: Jana se zajímá o děvčata, což jsou obvykle hubené děti. Tvrdí o nich:</i></p> Děvčata s velkou měrou podváhy jedí hnusné jídlo."}}],
[["it5-pl-e-nopsi", 5], aj, {s:  {html: "<p><i>Kontext: Jana pozorovala děvčata, z nichž některá snědla nevábná jídla. Tvrdí o nich:</i></p> Děvčata s velkou měrou podváhy jedí hnusné jídlo."}}],
[["it5-s-g-nopsi", 5], aj, {s:  {html: "<p><i>Kontext: Jana se zajímá o děvčata, což jsou obvykle hubené děti. Tvrdí o nich:</i></p> Děvče s velkou měrou podváhy jí hnusné jídlo."}}],
[["it5-s-e-nopsi", 5], aj, {s:  {html: "<p><i>Kontext: Jana pozorovala děvčata, z nichž některá snědla nevábná jídla. Tvrdí o nich:</i></p> Děvče s velkou měrou podváhy jí hnusné jídlo."}}],
[["it5-pl-g-psi", 5], aj, {s: {html: "<p><i>Kontext: Jana se zajímá o děvčata, což jsou obvykle hubené děti. Tvrdí o nich:</i></p> Děvčata se sebemenším náznakem podváhy jedí hnusné jídlo."}}],
[["it5-pl-e-psi", 5], aj, {s:  {html: "<p><i>Kontext: Jana pozorovala děvčata, z nichž některá snědla nevábná jídla. Tvrdí o nich:</i></p> Děvčata se sebemenším náznakem podváhy jedí hnusné jídlo."}}],
[["it5-s-g-psi", 5], aj, {s:  {html: "<p><i>Kontext: Jana se zajímá o děvčata, což jsou obvykle hubené děti. Tvrdí o nich:</i></p> Děvče se sebemenším náznakem podváhy jí hnusné jídlo."}}],
[["it5-s-e-psi", 5], aj, {s:  {html: "<p><i>Kontext: Jana pozorovala děvčata, z nichž některá snědla nevábná jídla. Tvrdí o nich:</i></p> Děvče se sebemenším náznakem podváhy jí hnusné jídlo."}}],
	     
[["it6-pl-g-nopsi", 6], aj, {s: {html: "<p><i>Kontext: Kuba se zajímá o kočky, což jsou obvykle pyšná zvířata. Tvrdí o nich:</i></p> Kočky s velkou měrou hrdosti dělají velký nepořádek."}}],
[["it6-pl-e-nopsi", 6], aj, {s: {html: "<p><i>Kontext: Kuba zkoumal kočky, z nichž některé shodily všechny věci. Tvrdí o nich:</i></p> Kočky s velkou měrou hrdosti dělají velký nepořádek."}}],
[["it6-s-g-nopsi", 6], aj, {s: {html: "<p><i>Kontext: Kuba se zajímá o kočky, což jsou obvykle pyšná zvířata. Tvrdí o nich:</i></p> Kočka s velkou měrou hrdosti dělá velký nepořádek."}}],
[["it6-s-e-nopsi", 6], aj, {s:  {html: "<p><i>Kontext: Kuba zkoumal kočky, z nichž některé shodily všechny věci. Tvrdí o nich:</i></p> Kočka s velkou měrou hrdosti dělá velký nepořádek."}}],
[["it6-pl-g-psi", 6], aj, {s: {html: "<p><i>Kontext: Kuba se zajímá o kočky, což jsou obvykle pyšná zvířata. Tvrdí o nich:</i></p> Kočky se sebemenším náznakem hrdosti dělají velký nepořádek."}}],
[["it6-pl-e-psi", 6], aj, {s: {html: "<p><i>Kontext: Kuba zkoumal kočky, z nichž některé shodily všechny věci. Tvrdí o nich:</i></p> Kočky se sebemenším náznakem hrdosti dělají velký nepořádek."}}],
[["it6-s-g-psi", 6], aj, {s: {html: "<p><i>Kontext: Kuba se zajímá o kočky, což jsou obvykle pyšná zvířata. Tvrdí o nich:</i></p> Kočka se sebemenším náznakem hrdosti dělá velký nepořádek."}}],
[["it6-s-e-psi", 6], aj, {s:  {html: "<p><i>Kontext: Kuba zkoumal kočky, z nichž některé shodily všechny věci. Tvrdí o nich:</i></p> Kočka se sebemenším náznakem hrdosti dělá velký nepořádek."}}],
	     
[["it7-pl-g-nopsi", 7], aj, {s: {html: "<p><i>Kontext: Darek se zajímá o muly, což jsou obvykle houževnatá zvířata. Tvrdí o nich:</i></p> Muly s velkou měrou zdatnosti nosí těžký náklad."}}],
[["it7-pl-e-nopsi", 7], aj, {s: {html: "<p><i>Kontext: Darek sledoval muly, z nichž některé dostaly velmi zabrat. Tvrdí o nich:</i></p> Muly s velkou měrou zdatnosti nosí těžký náklad."}}],
[["it7-s-g-nopsi", 7], aj, {s: {html: "<p><i>Kontext: Darek se zajímá o muly, což jsou obvykle houževnatá zvířata. Tvrdí o nich:</i></p> Mula s velkou měrou zdatnosti nosí těžký náklad."}}],
[["it7-s-e-nopsi", 7], aj, {s: {html: "<p><i>Kontext: Darek sledoval muly, z nichž některé dostaly velmi zabrat. Tvrdí o nich:</i></p> Mula s velkou měrou zdatnosti nosí těžký náklad."}}],
[["it7-pl-g-psi", 7], aj, {s: {html: "<p><i>Kontext: Darek se zajímá o muly, což jsou obvykle houževnatá zvířata. Tvrdí o nich:</i></p> Muly se sebemenší trochou zdatnosti nosí těžký náklad."}}],
[["it7-pl-e-psi", 7], aj, {s: {html: "<p><i>Kontext: Darek sledoval muly, z nichž některé dostaly velmi zabrat. Tvrdí o nich:</i></p> Muly se sebemenší trochou zdatnosti nosí těžký náklad."}}],
[["it7-s-g-psi", 7], aj, {s: {html: "<p><i>Kontext: Darek se zajímá o muly, což jsou obvykle houževnatá zvířata. Tvrdí o nich:</i></p> Mula se sebemenší trochou zdatnosti nosí těžký náklad."}}],
[["it7-s-e-psi", 7], aj, {s: {html: "<p><i>Kontext: Darek sledoval muly, z nichž některé dostaly velmi zabrat. Tvrdí o nich:</i></p> Mula se sebemenší trochou zdatnosti nosí těžký náklad."}}],
	     
[["it8-pl-g-nopsi", 8], aj, {s: {html: "<p><i>Kontext: Jiřka se zajímá o jasnovidky, což jsou obvykle mystické ženy. Tvrdí o nich:</i></p> Jasnovidky s vysokou úrovní nadání vidí smutnou budoucnost."}}],
[["it8-pl-e-nopsi", 8], aj, {s: {html: "<p><i>Kontext: Jiřka vyzpovídala jasnovidky, z nichž některé vyvěštily samé trápení. Tvrdí o nich:</i></p> Jasnovidky s vysokou úrovní nadání vidí smutnou budoucnost."}}],
[["it8-s-g-nopsi", 8], aj, {s: {html: "<p><i>Kontext: Jiřka se zajímá o jasnovidky, což jsou obvykle mystické ženy. Tvrdí o nich:</i></p> Jasnovidka s vysokou úrovní nadání vidí smutnou budoucnost."}}],
[["it8-s-e-nopsi", 8], aj, {s: {html: "<p><i>Kontext: Jiřka vyzpovídala jasnovidky, z nichž některé vyvěštily samé trápení. Tvrdí o nich:</i></p> Jasnovidka s vysokou úrovní nadání vidí smutnou budoucnost."}}],
[["it8-pl-g-psi", 8], aj, {s: {html: "<p><i>Kontext: Jiřka se zajímá o jasnovidky, což jsou obvykle mystické ženy. Tvrdí o nich:</i></p> Jasnovidky se sebemenší známkou nadání vidí smutnou budoucnost."}}],
[["it8-pl-e-psi", 8], aj, {s: {html: "<p><i>Kontext: Jiřka vyzpovídala jasnovidky, z nichž některé vyvěštily samé trápení. Tvrdí o nich:</i></p> Jasnovidky se sebemenší známkou nadání vidí smutnou budoucnost."}}],
[["it8-s-g-psi", 8], aj, {s: {html: "<p><i>Kontext: Jiřka se zajímá o jasnovidky, což jsou obvykle mystické ženy. Tvrdí o nich:</i></p> Jasnovidka se sebemenší známkou nadání vidí smutnou budoucnost."}}],
[["it8-s-e-psi", 8], aj, {s: {html: "<p><i>Kontext: Jiřka vyzpovídala jasnovidky, z nichž některé vyvěštily samé trápení. Tvrdí o nich:</i></p> Jasnovidka se sebemenší známkou nadání vidí smutnou budoucnost."}}],
	     
[["it9-pl-g-nopsi", 9], aj, {s: {html: "<p><i>Kontext: Zdena se zajímá o děti, což jsou obvykle nenasytní tvorové. Tvrdí o nich:</i></p> Děti s velkou měrou mlsnosti jedí prošlé cukroví."}}],
[["it9-pl-e-nopsi", 9], aj, {s: {html: "<p><i>Kontext: Zdena pozorovala děti, z nichž některým nevadí staré potraviny. Tvrdí o nich:</i></p> Děti s velkou měrou mlsnosti jedí prošlé cukroví."}}],
[["it9-s-g-nopsi", 9], aj, {s: {html: "<p><i>Kontext: Zdena se zajímá o děti, což jsou obvykle nenasytní tvorové. Tvrdí o nich:</i></p> Dítě s velkou měrou mlsnosti jí prošlé cukroví."}}],
[["it9-s-e-nopsi", 9], aj, {s: {html: "<p><i>Kontext: Zdena pozorovala děti, z nichž některým nevadí staré potraviny. Tvrdí o nich:</i></p> Dítě s velkou měrou mlsnosti jí prošlé cukroví."}}],
[["it9-pl-g-psi", 9], aj, {s: {html: "<p><i>Kontext: Zdena se zajímá o děti, což jsou obvykle nenasytní tvorové. Tvrdí o nich:</i></p> Děti se sebemenší trochou mlsnosti jedí prošlé cukroví."}}],
[["it9-pl-e-psi", 9], aj, {s: {html: "<p><i>Kontext: Zdena pozorovala děti, z nichž některým nevadí staré potraviny. Tvrdí o nich:</i></p> Děti se sebemenší trochou mlsnosti jedí prošlé cukroví."}}],
[["it9-s-g-psi", 9], aj, {s: {html: "<p><i>Kontext: Zdena se zajímá o děti, což jsou obvykle nenasytní tvorové. Tvrdí o nich:</i></p> Dítě se sebemenší trochou mlsnosti jí prošlé cukroví."}}],
[["it9-s-e-psi", 9], aj, {s: {html: "<p><i>Kontext: Zdena pozorovala děti, z nichž některým nevadí staré potraviny. Tvrdí o nich:</i></p> Dítě se sebemenší trochou mlsnosti jí prošlé cukroví."}}],
	     
[["it10-pl-g-nopsi", 10], aj, {s: {html: "<p><i>Kontext: David se zajímá o kritiky, což jsou obvykle přísní lidé. Tvrdí o nich:</i></p> Kritici s vysokou úrovní vkusu slyší špatnou hudbu."}}],
[["it10-pl-e-nopsi", 10], aj, {s: {html: "<p><i>Kontext: David vyzpovídal kritiky, z nichž někteří vnímali koncert negativně. Tvrdí o nich:</i></p> Kritici s vysokou úrovní vkusu slyší špatnou hudbu."}}],
[["it10-s-g-nopsi", 10], aj, {s: {html: "<p><i>Kontext: David se zajímá o kritiky, což jsou obvykle přísní lidé. Tvrdí o nich:</i></p> Kritik s vysokou úrovní vkusu slyší špatnou hudbu."}}],
[["it10-s-e-nopsi", 10], aj, {s: {html: "<p><i>Kontext: David vyzpovídal kritiky, z nichž někteří vnímali koncert negativně. Tvrdí o nich:</i></p> Kritik s vysokou úrovní vkusu slyší špatnou hudbu."}}],
[["it10-pl-g-psi", 10], aj, {s: {html: "<p><i>Kontext: David se zajímá o kritiky, což jsou obvykle přísní lidé. Tvrdí o nich:</i></p> Kritici se sebemenší známkou vkusu slyší špatnou hudbu."}}],
[["it10-pl-e-psi", 10], aj, {s: {html: "<p><i>Kontext: David vyzpovídal kritiky, z nichž někteří vnímali koncert negativně. Tvrdí o nich:</i></p> Kritici se sebemenší známkou vkusu slyší špatnou hudbu."}}],
[["it10-s-g-psi", 10], aj, {s: {html: "<p><i>Kontext: David se zajímá o kritiky, což jsou obvykle přísní lidé. Tvrdí o nich:</i></p> Kritik se sebemenší známkou vkusu slyší špatnou hudbu."}}],
[["it10-s-e-psi", 10], aj, {s: {html: "<p><i>Kontext: David vyzpovídal kritiky, z nichž někteří vnímali koncert negativně. Tvrdí o nich:</i></p> Kritik se sebemenší známkou vkusu slyší špatnou hudbu."}}],
	     
[["it11-pl-g-nopsi", 11], aj, {s: {html: "<p><i>Kontext: Lenka se zajímá o básnířky, což jsou obvykle emocionální ženy. Tvrdí o nich:</i></p> Básnířky s velkou silou citu píší dojemnou poezii."}}],
[["it11-pl-e-nopsi", 11], aj, {s: {html: "<p><i>Kontext: Lenka zkoumala básnířky, z nichž některé stvořily úžasné básně. Tvrdí o nich:</i></p> Básnířky s velkou silou citu píší dojemnou poezii."}}],
[["it11-s-g-nopsi", 11], aj, {s: {html: "<p><i>Kontext: Lenka se zajímá o básnířky, což jsou obvykle emocionální ženy. Tvrdí o nich:</i></p>Básnířka s velkou silou citu píše dojemnou poezii."}}],
[["it11-s-e-nopsi", 11], aj, {s: {html: "<p><i>Kontext: Lenka zkoumala básnířky, z nichž některé stvořily úžasné básně. Tvrdí o nich:</i></p>Básnířka s velkou silou citu píše dojemnou poezii."}}],
[["it11-pl-g-psi", 11], aj, {s: {html: "<p><i>Kontext: Lenka se zajímá o básnířky, což jsou obvykle emocionální ženy. Tvrdí o nich:</i></p> Básnířky se sebemenším náznakem citu píší dojemnou poezii."}}],
[["it11-pl-e-psi", 11], aj, {s: {html: "<p><i>Kontext: Lenka zkoumala básnířky, z nichž některé stvořily úžasné básně. Tvrdí o nich:</i></p> Básnířky se sebemenším náznakem citu píší dojemnou poezii."}}],
[["it11-s-g-psi", 11], aj, {s: {html: "<p><i>Kontext: Lenka se zajímá o básnířky, což jsou obvykle emocionální ženy. Tvrdí o nich:</i></p>Básnířka se sebemenším náznakem citu píše dojemnou poezii."}}],
[["it11-s-e-psi", 11], aj, {s: {html: "<p><i>Kontext: Lenka zkoumala básnířky, z nichž některé stvořily úžasné básně. Tvrdí o nich:</i></p>Básnířka se sebemenším náznakem citu píše dojemnou poezii."}}],

[["it12-pl-g-nopsi", 12], aj, {s: {html: "<p><i>Kontext: Hanka se zajímá o ohaře, což jsou obvykle temperamentní psi. Tvrdí o nich:</i></p> Ohaři s velkou měrou agresivity nosí zabitou kořist."}}],
[["it12-pl-e-nopsi", 12], aj, {s: {html: "<p><i>Kontext: Hanka sledovala ohaře, z nichž někteří zvládli dobře aportovat. Tvrdí o nich:</i></p> Ohaři s velkou měrou agresivity nosí zabitou kořist."}}],
[["it12-s-g-nopsi", 12], aj, {s: {html: "<p><i>Kontext: Hanka se zajímá o ohaře, což jsou obvykle temperamentní psi. Tvrdí o nich:</i></p> Ohař s velkou měrou agresivity nosí zabitou kořist."}}],
[["it12-s-e-nopsi", 12], aj, {s: {html: "<p><i>Kontext: Hanka sledovala ohaře, z nichž někteří zvládli dobře aportovat. Tvrdí o nich:</i></p> Ohař s velkou měrou agresivity nosí zabitou kořist."}}],
[["it12-pl-g-psi", 12], aj, {s: {html: "<p><i>Kontext: Hanka se zajímá o ohaře, což jsou obvykle temperamentní psi. Tvrdí o nich:</i></p> Ohaři se sebemenším projevem agresivity nosí zabitou kořist."}}],
[["it12-pl-e-psi", 12], aj, {s: {html: "<p><i>Kontext: Hanka sledovala ohaře, z nichž někteří zvládli dobře aportovat. Tvrdí o nich:</i></p> Ohaři se sebemenším projevem agresivity nosí zabitou kořist."}}],
[["it12-s-g-psi", 12], aj, {s: {html: "<p><i>Kontext: Hanka se zajímá o ohaře, což jsou obvykle temperamentní psi. Tvrdí o nich:</i></p> Ohař se sebemenším projevem agresivity nosí zabitou kořist."}}],
[["it12-s-e-psi", 12], aj, {s: {html: "<p><i>Kontext: Hanka sledovala ohaře, z nichž někteří zvládli dobře aportovat. Tvrdí o nich:</i></p> Ohař se sebemenším projevem agresivity nosí zabitou kořist."}}],	    

[["it13-pl-g-nopsi", 13], aj, {s: {html: "<p><i>Kontext: Pavel se zajímá o lyžařky, což jsou obvykle ostřílené sportovkyně. Tvrdí o nich:</i></p> Lyžařky s velkou měrou zkušenosti jezdí dobrý slalom."}}],
[["it13-pl-e-nopsi", 13], aj, {s: {html: "<p><i>Kontext: Pavel pozoroval lyžařky, z nichž některé podaly úžasný výkon. Tvrdí o nich:</i></p> Lyžařky s velkou měrou zkušenosti jezdí dobrý slalom."}}],
[["it13-s-g-nopsi", 13], aj, {s: {html: "<p><i>Kontext: Pavel se zajímá o lyžařky, což jsou obvykle ostřílené sportovkyně. Tvrdí o nich:</i></p> Lyžařka s velkou měrou zkušenosti jezdí dobrý slalom."}}],
[["it13-s-e-nopsi", 13], aj, {s: {html: "<p><i>Kontext: Pavel pozoroval lyžařky, z nichž některé podaly úžasný výkon. Tvrdí o nich:</i></p> Lyžařka s velkou měrou zkušenosti jezdí dobrý slalom."}}],
[["it13-pl-g-psi", 13], aj, {s: {html: "<p><i>Kontext: Pavel se zajímá o lyžařky, což jsou obvykle ostřílené sportovkyně. Tvrdí o nich:</i></p> Lyžařky se sebemenší známkou zkušenosti jezdí dobrý slalom."}}],
[["it13-pl-e-psi", 13], aj, {s: {html: "<p><i>Kontext: Pavel pozoroval lyžařky, z nichž některé podaly úžasný výkon. Tvrdí o nich:</i></p> Lyžařky se sebemenší známkou zkušenosti jezdí dobrý slalom."}}],
[["it13-s-g-psi", 13], aj, {s: {html: "<p><i>Kontext: Pavel se zajímá o lyžařky, což jsou obvykle ostřílené sportovkyně. Tvrdí o nich:</i></p> Lyžařka se sebemenší známkou zkušenosti jezdí dobrý slalom."}}],
[["it13-s-e-psi", 13], aj, {s: {html: "<p><i>Kontext: Pavel pozoroval lyžařky, z nichž některé podaly úžasný výkon. Tvrdí o nich:</i></p> Lyžařka se sebemenší známkou zkušenosti jezdí dobrý slalom."}}],
	     
[["it14-pl-g-nopsi", 14], aj, {s: {html: "<p><i>Kontext: Marek se zajímá o herečky, což jsou obvykle nadané umělkyně. Tvrdí o nich:</i></p> Herečky s velkou měrou talentu hrají působivé drama."}}],
[["it14-pl-e-nopsi", 14], aj, {s: {html: "<p><i>Kontext: Marek sledoval herečky, z nichž některé dojaly každého diváka. Tvrdí o nich:</i></p> Herečky s velkou měrou talentu hrají působivé drama."}}],
[["it14-s-g-nopsi", 14], aj, {s: {html: "<p><i>Kontext: Marek se zajímá o herečky, což jsou obvykle nadané umělkyně. Tvrdí o nich:</i></p> Herečka s velkou měrou talentu hraje působivé drama."}}],
[["it14-s-e-nopsi", 14], aj, {s: {html: "<p><i>Kontext: Marek sledoval herečky, z nichž některé dojaly každého diváka. Tvrdí o nich:</i></p> Herečka s velkou měrou talentu hraje působivé drama."}}],
[["it14-pl-g-psi", 14], aj, {s: {html: "<p><i>Kontext: Marek se zajímá o herečky, což jsou obvykle nadané umělkyně. Tvrdí o nich:</i></p> Herečky se sebemenší známkou talentu hrají působivé drama."}}],
[["it14-pl-e-psi", 14], aj, {s: {html: "<p><i>Kontext: Marek sledoval herečky, z nichž některé dojaly každého diváka. Tvrdí o nich:</i></p> Herečky se sebemenší známkou talentu hrají působivé drama."}}],
[["it14-s-g-psi", 14], aj, {s: {html: "<p><i>Kontext: Marek se zajímá o herečky, což jsou obvykle nadané umělkyně. Tvrdí o nich:</i></p> Herečka se sebemenší známkou talentu hraje působivé drama."}}],
[["it14-s-e-psi", 14], aj, {s: {html: "<p><i>Kontext: Marek sledoval herečky, z nichž některé dojaly každého diváka. Tvrdí o nich:</i></p> Herečka se sebemenší známkou talentu hraje působivé drama."}}],	     

[["it15-pl-g-nopsi", 15], aj, {s: {html: "<p><i>Kontext: Zora se zajímá o vědce, což jsou obvykle rozumní lidé. Tvrdí o nich:</i></p> Vědci s velkou měrou snahy dělají kvalitní práci."}}],
[["it15-pl-e-nopsi", 15], aj, {s: {html: "<p><i>Kontext: Zora zkoumala vědce, z nichž někteří vyvinuli špičkové metody. Tvrdí o nich:</i></p> Vědci s velkouu měrou snahy dělají kvalitní práci."}}],
[["it15-s-g-nopsi", 15], aj, {s: {html: "<p><i>Kontext: Zora se zajímá o vědce, což jsou obvykle rozumní lidé. Tvrdí o nich:</i></p> Vědec s velkou měrou snahy dělá kvalitní práci."}}],
[["it15-s-e-nopsi", 15], aj, {s: {html: "<p><i>Kontext: Zora zkoumala vědce, z nichž někteří vyvinuli špičkové metody. Tvrdí o nich:</i></p> Vědec s velkou měrou snahy dělá kvalitní práci."}}],
[["it15-pl-g-psi", 15], aj, {s: {html: "<p><i>Kontext: Zora se zajímá o vědce, což jsou obvykle rozumní lidé. Tvrdí o nich:</i></p> Vědci se sebemenším projevem snahy dělají kvalitní práci."}}],
[["it15-pl-e-psi", 15], aj, {s: {html: "<p><i>Kontext: Zora zkoumala vědce, z nichž někteří vyvinuli špičkové metody. Tvrdí o nich:</i></p> Vědci se sebemenším projevem snahy dělají kvalitní práci."}}],
[["it15-s-g-psi", 15], aj, {s: {html: "<p><i>Kontext: Zora se zajímá o vědce, což jsou obvykle rozumní lidé. Tvrdí o nich:</i></p> Vědec se sebemenším projevem snahy dělá kvalitní práci."}}],
[["it15-s-e-psi", 15], aj, {s: {html: "<p><i>Kontext: Zora zkoumala vědce, z nichž někteří vyvinuli špičkové metody. Tvrdí o nich:</i></p> Vědec se sebemenším projevem snahy dělá kvalitní práci."}}],

[["it16-pl-g-nopsi", 16], aj, {s: {html: "<p><i>Kontext: Pepa se zajímá o běžce, což jsou obvykle vytrvalí lidé. Tvrdí o nich:</i></p> Běžci s velkou měrou disciplíny běhají dobrý maraton."}}],
[["it16-pl-e-nopsi", 16], aj, {s: {html: "<p><i>Kontext: Pepa pozoroval běžce, z nichž někteří doběhli závod brzy. Tvrdí o nich:</i></p> Běžci s velkou měrou disciplíny běhají dobrý maraton."}}],
[["it16-s-g-nopsi", 16], aj, {s: {html: "<p><i>Kontext: Pepa se zajímá o běžce, což jsou obvykle vytrvalí lidé. Tvrdí o nich:</i></p> Běžec s velkou měrou disciplíny běhá dobrý maraton."}}],
[["it16-s-e-nopsi", 16], aj, {s: {html: "<p><i>Kontext: Pepa pozoroval běžce, z nichž někteří doběhli závod brzy. Tvrdí o nich:</i></p> Běžec s velkou měrou disciplíny běhá dobrý maraton."}}],
[["it16-pl-g-psi", 16], aj, {s: {html: "<p><i>Kontext: Pepa se zajímá o běžce, což jsou obvykle vytrvalí lidé. Tvrdí o nich:</i></p> Běžci se sebemenší trochou disciplíny běhají dobrý maraton."}}],
[["it16-pl-e-psi", 16], aj, {s: {html: "<p><i>Kontext: Pepa pozoroval běžce, z nichž někteří doběhli závod brzy. Tvrdí o nich:</i></p> Běžci se sebemenší trochou disciplíny běhají dobrý maraton."}}],
[["it16-s-g-psi", 16], aj, {s: {html: "<p><i>Kontext: Pepa se zajímá o běžce, což jsou obvykle vytrvalí lidé. Tvrdí o nich:</i></p> Běžec se sebemenší trochou disciplíny běhá dobrý maraton."}}],
[["it16-s-e-psi", 16], aj, {s: {html: "<p><i>Kontext: Pepa pozoroval běžce, z nichž někteří doběhli závod brzy. Tvrdí o nich:</i></p> Běžec se sebemenší trochou disciplíny běhá dobrý maraton."}}],

[["it17-pl-g-nopsi", 17], aj, {s: {html: "<p><i>Kontext: Blanka se zajímá o šprty, což jsou obvykle ambiciózní děti. Tvrdí o nich:</i></p> Šprti s velkou měrou ambice hrají trojrozměrné šachy."}}],
[["it17-pl-e-nopsi", 17], aj, {s: {html: "<p><i>Kontext: Blanka pozorovala šprty, z nichž někteří dokončili partii 3D šachů. Tvrdí o nich:</i></p> Šprti s velkou měrou ambice hrají trojrozměrné šachy."}}],
[["it17-s-g-nopsi", 17], aj, {s: {html: "<p><i>Kontext: Blanka se zajímá o šprty, což jsou obvykle ambiciózní děti. Tvrdí o nich:</i></p> Šprt s velkou měrou ambice hraje trojrozměrné šachy."}}],
[["it17-s-e-nopsi", 17], aj, {s: {html: "<p><i>Kontext: Blanka pozorovala šprty, z nichž někteří dokončili partii 3D šachů. Tvrdí o nich:</i></p> Šprt s velkou měrou ambice hraje trojrozměrné šachy."}}],
[["it17-pl-g-psi", 17], aj, {s: {html: "<p><i>Kontext: Blanka se zajímá o šprty, což jsou obvykle ambiciózní děti. Tvrdí o nich:</i></p> Šprti se sebemenší známkou ambice hrají 3D šachy."}}],
[["it17-pl-e-psi", 17], aj, {s: {html: "<p><i>Kontext: Blanka pozorovala šprty, z nichž někteří dokončili partii 3D šachů. Tvrdí o nich:</i></p> Šprti se sebemenší známkou ambice hrají 3D šachy."}}],
[["it17-s-g-psi", 17], aj, {s: {html: "<p><i>Kontext: Blanka se zajímá o šprty, což jsou obvykle ambiciózní děti. Tvrdí o nich:</i></p> Šprt se sebemenší známkou ambice hraje 3D šachy."}}],
[["it17-s-e-psi", 17], aj, {s: {html: "<p><i>Kontext: Blanka pozorovala šprty, z nichž někteří dokončili partii 3D šachů. Tvrdí o nich:</i></p> Šprt se sebemenší známkou ambice hraje 3D šachy."}}],

[["it18-pl-g-nopsi", 18], aj, {s: {html: "<p><i>Kontext: Květa se zajímá o hlídače, což jsou obvykle bystří zaměstnanci. Tvrdí o nich:</i></p> Hlídači s velkou měrou všímavosti vidí podezřelou činnost."}}],
[["it18-pl-e-nopsi", 18], aj, {s: {html: "<p><i>Kontext: Květa vyzpovídala hlídače, z nichž někteří sáhli po zbraních. Tvrdí o nich: </i></p> Hlídači s velkou měrou všímavosti vidí podezřelou činnost."}}],
[["it18-s-g-nopsi", 18], aj, {s: {html: "<p><i>Kontext: Květa se zajímá o hlídače, což jsou obvykle bystří zaměstnanci. Tvrdí o nich:</i></p> Hlídač s velkou měrou všímavosti vidí podezřelou činnost."}}],
[["it18-s-e-nopsi", 18], aj, {s: {html: "<p><i>Kontext: Květa vyzpovídala hlídače, z nichž někteří sáhli po zbraních. Tvrdí o nich:</i></p> Hlídač s velkou měrou všímavosti vidí podezřelou činnost."}}],
[["it18-pl-g-psi", 18], aj, {s: {html: "<p><i>Kontext: Květa se zajímá o hlídače, což jsou obvykle bystří zaměstnanci. Tvrdí o nich:</i></p> Hlídači se sebemenší trochou všímavosti vidí podezřelou činnost."}}],
[["it18-pl-e-psi", 18], aj, {s: {html: "<p><i>Kontext: Květa vyzpovídala hlídače, z nichž někteří sáhli po zbraních. Tvrdí o nich:</i></p> Hlídači se sebemenší trochou všímavosti vidí podezřelou činnost."}}],
[["it18-s-g-psi", 18], aj, {s: {html: "<p><i>Kontext: Květa se zajímá o hlídače, což jsou obvykle bystří zaměstnanci. Tvrdí o nich:</i></p> Hlídač se sebemenší trochou všímavosti vidí podezřelou činnost."}}],
[["it18-s-e-psi", 18], aj, {s: {html: "<p><i>Kontext: Květa vyzpovídala hlídače, z nichž někteří sáhli po zbraních. Tvrdí o nich:</i></p> Hlídač se sebemenší trochou všímavosti vidí podezřelou činnost."}}],
	     
[["it19-pl-g-nopsi", 19], aj, {s: {html: "<p><i>Kontext: Tonda se zajímá o krysy, což jsou obvykle chytrá zvířata. Tvrdí o nich:</i></p> Krysy s vysokou úrovní inteligence jedí čerstvou potravu."}}],
[["it19-pl-e-nopsi", 19], aj, {s: {html: "<p><i>Kontext: Tonda pozoroval krysy, z nichž některé spořádaly nové granule. Tvrdí o nich: </i></p> Krysy s vysokou úrovní inteligence jedí čerstvou potravu."}}],
[["it19-s-g-nopsi", 19], aj, {s: {html: "<p><i>Kontext: Tonda se zajímá o krysy, což jsou obvykle chytrá zvířata. Tvrdí o nich:</i></p> Krysa s vysokou úrovní inteligence jí čerstvou potravu."}}],
[["it19-s-e-nopsi", 19], aj, {s: {html: "<p><i>Kontext: Tonda pozoroval krysy, z nichž některé spořádaly nové granule. Tvrdí o nich:</i></p> Krysa s vysokou úrovní inteligence jí čerstvou potravu."}}],
[["it19-pl-g-psi", 19], aj, {s: {html: "<p><i>Kontext: Tonda se zajímá o krysy, což jsou obvykle chytrá zvířata. Tvrdí o nich:</i></p> Krysy se sebemenší známkou inteligence jedí čerstvou potravu."}}],
[["it19-pl-e-psi", 19], aj, {s: {html: "<p><i>Kontext: Tonda pozoroval krysy, z nichž některé spořádaly nové granule. Tvrdí o nich: </i></p> Krysy se sebemenší známkou inteligence jedí čerstvou potravu."}}],
[["it19-s-g-psi", 19], aj, {s: {html: "<p><i>Kontext: Tonda se zajímá o krysy, což jsou obvykle chytrá zvířata. Tvrdí o nich:</i></p> Krysa se sebemenší známkou inteligence jí čerstvou potravu."}}],
[["it19-s-e-psi", 19], aj, {s: {html: "<p><i>Kontext: Tonda pozoroval krysy, z nichž některé spořádaly nové granule. Tvrdí o nich:</i></p> Krysa se sebemenší známkou inteligence jí čerstvou potravu."}}],

[["it20-pl-g-nopsi", 20], aj, {s: {html: "<p><i>Kontext: Evžen se zajímá o političky, což jsou obvykle nezávislé ženy. Tvrdí o nich:</i></p> Političky s vysokou úrovní individuality slyší hloupé řeči."}}],
[["it20-pl-e-nopsi", 20], aj, {s: {html: "<p><i>Kontext: Evžen sledoval političky, z nichž některé zažily slovní útok. Tvrdí o nich:</i></p> Političky s vysokou úrovní individuality slyší hloupé řeči."}}],
[["it20-s-g-nopsi", 20], aj, {s: {html: "<p><i>Kontext: Evžen se zajímá o političky, což jsou obvykle nezávislé ženy. Tvrdí o nich:</i></p> Politička s vysokou úrovní individuality slyší hloupé řeči."}}],
[["it20-s-e-nopsi", 20], aj, {s: {html: "<p><i>Kontext: Evžen sledoval političky, z nichž některé zažily slovní útok. Tvrdí o nich:</i></p> Politička s vysokou úrovní individuality slyší hloupé řeči."}}],
[["it20-pl-g-psi", 20], aj, {s: {html: "<p><i>Kontext: Evžen se zajímá o političky, což jsou obvykle nezávislé ženy. Tvrdí o nich:</i></p> Političky se sebemenším projevem individuality slyší hloupé řeči."}}],
[["it20-pl-e-psi", 20], aj, {s: {html: "<p><i>Kontext: Evžen sledoval političky, z nichž některé zažily slovní útok. Tvrdí o nich:</i></p> Političky se sebemenším projevem individuality slyší hloupé řeči."}}],
[["it20-s-g-psi", 20], aj, {s: {html: "<p><i>Kontext: Evžen se zajímá o političky, což jsou obvykle nezávislé ženy. Tvrdí o nich:</i></p> Politička se sebemenším projevem individuality slyší hloupé řeči."}}],
[["it20-s-e-psi", 20], aj, {s: {html: "<p><i>Kontext: Evžen sledoval političky, z nichž některé zažily slovní útok. Tvrdí o nich:</i></p> Politička se sebemenším projevem individuality slyší hloupé řeči."}}],
	     
[["it21-pl-g-nopsi", 21], aj, {s: {html: "<p><i>Kontext: Nora se zajímá o švadleny, což jsou obvykle šikovné řemeslnice. Tvrdí o nich:</i></p> Švadleny s velkou měrou zručnosti dělají hodnotné zboží."}}],
[["it21-pl-e-nopsi", 21], aj, {s: {html: "<p><i>Kontext: Nora pozorovala švadleny, z nichž některé ušily přepychové šaty. Tvrdí o nich:</i></p> Švadleny s velkou měrou zručnosti dělají hodnotné zboží."}}],
[["it21-s-g-nopsi", 21], aj, {s: {html: "<p><i>Kontext: Nora se zajímá o švadleny, což jsou obvykle šikovné řemeslnice. Tvrdí o nich:</i></p> Švadlena s velkou měrou zručnosti dělá hodnotné zboží."}}],
[["it21-s-e-nopsi", 21], aj, {s: {html: "<p><i>Kontext: Nora pozorovala švadleny, z nichž některé ušily přepychové šaty. Tvrdí o nich:</i></p> Švadlena s velkou měrou zručnosti dělá hodnotné zboží."}}],
[["it21-pl-g-psi", 21], aj, {s: {html: "<p><i>Kontext: Nora se zajímá o švadleny, což jsou obvykle šikovné řemeslnice. Tvrdí o nich:</i></p> Švadleny se sebemenší trochou zručnosti dělají hodnotné zboží."}}],
[["it21-pl-e-psi", 21], aj, {s: {html: "<p><i>Kontext: Nora pozorovala švadleny, z nichž některé ušily přepychové šaty. Tvrdí o nich:</i></p> Švadleny se sebemenší trochou zručnosti dělají hodnotné zboží."}}],
[["it21-s-g-psi", 21], aj, {s: {html: "<p><i>Kontext: Nora se zajímá o švadleny, což jsou obvykle šikovné řemeslnice. Tvrdí o nich:</i></p> Švadlena se sebemenší trochou zručnosti dělá hodnotné zboží."}}],
[["it21-s-e-psi", 21], aj, {s: {html: "<p><i>Kontext: Nora pozorovala švadleny, z nichž některé ušily přepychové šaty. Tvrdí o nich:</i></p> Švadlena se sebemenší trochou zručnosti dělá hodnotné zboží."}}],

[["it22-pl-g-nopsi", 22], aj, {s: {html: "<p><i>Kontext: Jenda se zajímá o středoškoláky, což jsou obvykle líní lidé. Tvrdí o nich:</i></p> Středoškoláci s velkou měrou lenosti nosí špatné vysvědčení."}}],
[["it22-pl-e-nopsi", 22], aj, {s: {html: "<p><i>Kontext: Jenda zkoumal středoškoláky, z nichž někteří málem nedokončili ročník. Tvrdí o nich:</i></p> Středoškoláci s velkou měrou lenosti nosí špatné vysvědčení."}}],
[["it22-s-g-nopsi", 22], aj, {s: {html: "<p><i>Kontext: Jenda se zajímá o středoškoláky, což jsou obvykle líní lidé. Tvrdí o nich:</i></p> Středoškolák s velkou měrou lenosti nosí špatné vysvědčení."}}],
[["it22-s-e-nopsi", 22], aj, {s: {html: "<p><i>Kontext: Jenda zkoumal středoškoláky, z nichž někteří málem nedokončili ročník. Tvrdí o nich:</i></p> Středoškolák s velkou měrou lenosti nosí špatné vysvědčení."}}],
[["it22-pl-g-psi", 22], aj, {s: {html: "<p><i>Kontext: Jenda se zajímá o středoškoláky, což jsou obvykle líní lidé. Tvrdí o nich:</i></p> Středoškoláci se sebemenším náznakem lenosti nosí špatné vysvědčení."}}],
[["it22-pl-e-psi", 22], aj, {s: {html: "<p><i>Kontext: Jenda zkoumal středoškoláky, z nichž někteří málem nedokončili ročník. Tvrdí o nich:</i></p> Středoškoláci se sebemenším náznakem lenosti nosí špatné vysvědčení."}}],
[["it22-s-g-psi", 22], aj, {s: {html: "<p><i>Kontext: Jenda se zajímá o středoškoláky, což jsou obvykle líní lidé. Tvrdí o nich:</i></p> Středoškolák se sebemenším náznakem lenosti nosí špatné vysvědčení."}}],
[["it22-s-e-psi", 22], aj, {s: {html: "<p><i>Kontext: Jenda zkoumal středoškoláky, z nichž někteří málem nedokončili ročník. Tvrdí o nich:</i></p> Středoškolák se sebemenším náznakem lenosti nosí špatné vysvědčení."}}],

[["it23-pl-g-nopsi", 23], aj, {s: {html: "<p><i>Kontext: Cyril se zajímá o trekaře, což jsou obvykle aktivní sportovci. Tvrdí o nich:</i></p> Trekaři s velkou měrou činorodosti chodí týdenní přechod."}}],
[["it23-pl-e-nopsi", 23], aj, {s: {html: "<p><i>Kontext: Cyril sledoval trekaře, z nichž někteří zrovna dorazili domů. Tvrdí o nich:</i></p> Trekaři s velkou měrou činorodosti chodí týdenní přechod."}}],
[["it23-s-g-nopsi", 23], aj, {s: {html: "<p><i>Kontext: Cyril se zajímá o trekaře, což jsou obvykle aktivní sportovci. Tvrdí o nich:</i></p> Trekař s velkou měrou činorodosti chodí týdenní přechod."}}],
[["it23-s-e-nopsi", 23], aj, {s: {html: "<p><i>Kontext: Cyril sledoval trekaře, z nichž někteří zrovna dorazili domů. Tvrdí o nich: </i></p> Trekař s velkou měrou činorodosti chodí týdenní přechod."}}],
[["it23-pl-g-psi", 23], aj, {s: {html: "<p><i>Kontext: Cyril se zajímá o trekaře, což jsou obvykle aktivní sportovci. Tvrdí o nich:</i></p> Trekaři se sebemenší trochou činorodosti chodí týdenní přechod."}}],
[["it23-pl-e-psi", 23], aj, {s: {html: "<p><i>Kontext: Cyril sledoval trekaře, z nichž někteří zrovna dorazili domů. Tvrdí o nich: </i></p> Trekaři se sebemenší trochou činorodosti chodí týdenní přechod."}}],
[["it23-s-g-psi", 23], aj, {s: {html: "<p><i>Kontext: Cyril se zajímá o trekaře, což jsou obvykle aktivní sportovci. Tvrdí o nich:</i></p> Trekař se sebemenší trochou činorodosti chodí týdenní přechod."}}],
[["it23-s-e-psi", 23], aj, {s: {html: "<p><i>Kontext: Cyril sledoval trekaře, z nichž někteří zrovna dorazili domů. Tvrdí o nich: </i></p> Trekař se sebemenší trochou činorodosti chodí týdenní přechod."}}],

[["it24-pl-g-nopsi", 24], aj, {s: {html: "<p><i>Kontext: Marie se zajímá o saxofonistky, což jsou obvykle inovativní hudebnice. Tvrdí o nich:</i></p> Saxofonistky s vysokou úrovní vynalézavosti hrají jazzovou improvizaci."}}],
[["it24-pl-e-nopsi", 24], aj, {s: {html: "<p><i>Kontext: Marie vyzpovídala saxofonistky, z nichž některé na koncertě improvizovaly. Tvrdí o nich:</i></p> Saxofonistky s vysokou úrovní vynalézavosti hrají jazzovou improvizaci."}}],
[["it24-s-g-nopsi", 24], aj, {s: {html: "<p><i>Kontext: Marie se zajímá o saxofonistky, což jsou obvykle inovativní hudebnice. Tvrdí o nich:</i></p> Saxofonistka s vysokou úrovní vynalézavosti hraje jazzovou improvizaci."}}],
[["it24-s-e-nopsi", 24], aj, {s: {html: "<p><i>Kontext: Marie vyzpovídala saxofonistky, z nichž některé na koncertě improvizovaly. Tvrdí o nich:</i></p> Saxofonistka s vysokou úrovní vynalézavosti hraje jazzovou improvizaci."}}],
[["it24-pl-g-psi", 24], aj, {s: {html: "<p><i>Kontext: Marie se zajímá o saxofonistky, což jsou obvykle inovativní hudebnice. Tvrdí o nich:</i></p> Saxofonistky se sebemenší známkou vynalézavosti hrají jazzovou improvizaci."}}],
[["it24-pl-e-psi", 24], aj, {s: {html: "<p><i>Kontext: Marie vyzpovídala saxofonistky, z nichž některé na koncertě improvizovaly. Tvrdí o nich:</i></p> Saxofonistky se sebemenší známkou vynalézavosti hrají jazzovou improvizaci."}}],
[["it24-s-g-psi", 24], aj, {s: {html: "<p><i>Kontext: Marie se zajímá o saxofonistky, což jsou obvykle inovativní hudebnice. Tvrdí o nich:</i></p> Saxofonistka se sebemenší známkou vynalézavosti hraje jazzovou improvizaci."}}],
[["it24-s-e-psi", 24], aj, {s: {html: "<p><i>Kontext: Marie vyzpovídala saxofonistky, z nichž některé na koncertě improvizovaly. Tvrdí o nich:</i></p> Saxofonistka se sebemenší známkou vynalézavosti hraje jazzovou improvizaci."}}],

[["it25-pl-g-nopsi", 25], aj, {s: {html: "<p><i>Kontext: Bětka se zajímá o kajakáře, což jsou obvykle dobrodružní lidé. Tvrdí o nich:</i></p> Kajakáři s velkou měrou odvahy jezdí divokou vodu."}}],
[["it25-pl-e-nopsi", 25], aj, {s: {html: "<p><i>Kontext: Bětka sledovala kajakáře, z nichž někteří překonávali přírodní překážky. Tvrdí o nich:</i></p>Kajakáři s velkou měrou odvahy jezdí divokou vodu."}}],
[["it25-s-g-nopsi", 25], aj, {s: {html: "<p><i>Kontext: Bětka se zajímá o kajakáře, což jsou obvykle dobrodružní lidé. Tvrdí o nich:</i></p> Kajakář s velkou měrou odvahy jezdí divokou vodu."}}],
[["it25-s-e-nopsi", 25], aj, {s: {html: "<p><i>Kontext: Bětka sledovala kajakáře, z nichž někteří překonávali přírodní překážky. Tvrdí o nich:</i></p> Kajakář s velkou měrou odvahy jezdí divokou vodu."}}],
[["it25-pl-g-psi", 25], aj, {s: {html: "<p><i>Kontext: Bětka se zajímá o kajakáře, což jsou obvykle dobrodružní lidé. Tvrdí o nich:</i></p> Kajakáři se sebemenší trochou odvahy jezdí divokou vodu."}}],
[["it25-pl-e-psi", 25], aj, {s: {html: "<p><i>Kontext: Bětka sledovala kajakáře, z nichž někteří překonávali přírodní překážky. Tvrdí o nich:</i></p> Kajakáři se sebemenší trochou odvahy jezdí divokou vodu."}}],
[["it25-s-g-psi", 25], aj, {s: {html: "<p><i>Kontext: Bětka se zajímá o kajakáře, což jsou obvykle dobrodružní lidé. Tvrdí o nich:</i></p> Kajakář se sebemenší trochou odvahy jezdí divokou vodu."}}],
[["it25-s-e-psi", 25], aj, {s: {html: "<p><i>Kontext: Bětka sledovala kajakáře, z nichž někteří překonávali přírodní překážky. Tvrdí o nich:</i></p> Kajakář se sebemenší trochou odvahy jezdí divokou vodu."}}],
	
[["it26-pl-g-nopsi", 26], aj, {s: {html: "<p><i>Kontext: Emil se zajímá o skladatele, co jsou obvykle divadelní nadšenci. Tvrdí o nich:</i></p> Skladatelé s velkou měrou vášně píší velkolepou operu."}}],
[["it26-pl-e-nopsi", 26], aj, {s: {html: "<p><i>Kontext: Emil zkoumal skladatele, z nichž někteří dokončili nová díla. Tvrdí o nich:</i></p> Skladatelé s velkou měrou vášně píší velkolepou operu."}}],
[["it26-s-g-nopsi", 26], aj, {s: {html: "<p><i>Kontext: Emil se zajímá o skladatele, co jsou obvykle divadelní nadšenci. Tvrdí o nich:</i></p> Skladatel s velkou měrou vášně píše velkolepou operu."}}],
[["it26-s-e-nopsi", 26], aj, {s: {html: "<p><i>Kontext: Emil zkoumal skladatele, z nichž někteří dokončili nová díla. Tvrdí o nich:</i></p> Skladatel s velkou měrou vášně píše velkolepou operu."}}],
[["it26-pl-g-psi", 26], aj, {s: {html: "<p><i>Kontext: Emil se zajímá o skladatele, co jsou obvykle divadelní nadšenci. Tvrdí o nich:</i></p> Skladatelé se sebemenší známkou vášně píší velkolepou operu."}}],
[["it26-pl-e-psi", 26], aj, {s: {html: "<p><i>Kontext: Emil zkoumal skladatele, z nichž někteří dokončili nová díla. Tvrdí o nich:</i></p> Skladatelé se sebemenší známkou vášně píší velkolepou operu."}}],
[["it26-s-g-psi", 26], aj, {s: {html: "<p><i>Kontext: Emil se zajímá o skladatele, co jsou obvykle divadelní nadšenci. Tvrdí o nich:</i></p> Skladatel se sebemenší známkou vášně píše velkolepou operu."}}],
[["it26-s-e-psi", 26], aj, {s: {html: "<p><i>Kontext: Emil zkoumal skladatele, z nichž někteří dokončili nová díla. Tvrdí o nich:</i></p> Skladatel se sebemenší známkou vášně píše velkolepou operu."}}],

[["it27-pl-g-nopsi", 27], aj, {s: {html: "<p><i>Kontext: Karel se zajímá o cyklóny, což jsou obvykle sněhové vánice. Tvrdí o nich:</i></p> Cyklóny s velkým množstvím sněhu dělají strašnou paseku."}}],
[["it27-pl-e-nopsi", 27], aj, {s: {html: "<p><i>Kontext: Karel zkoumal cyklóny, z nichž některé napáchaly velké škody. Tvrdí o nich:</i></p> Cyklóny s velkým množstvím sněhu dělají strašnou paseku."}}],
[["it27-s-g-nopsi", 27], aj, {s: {html: "<p><i>Kontext: Karel se zajímá o cyklóny, což jsou obvykle sněhové vánice. Tvrdí o nich:</i></p> Cyklóna s velkým množstvím sněhu dělá strašnou paseku."}}],
[["it27-s-e-nopsi", 27], aj, {s: {html: "<p><i>Kontext: Karel zkoumal cyklóny, z nichž některé napáchaly velké škody. Tvrdí o nich:</i></p> Cyklóna s velkým množstvím sněhu dělá strašnou paseku."}}],
[["it27-pl-g-psi", 27], aj, {s: {html: "<p><i>Kontext: Karel se zajímá o cyklóny, což jsou obvykle sněhové vánice. Tvrdí o nich:</i></p> Cyklóny se sebemenší trochou sněhu dělají strašnou paseku."}}],
[["it27-pl-e-psi", 27], aj, {s: {html: "<p><i>Kontext: Karel zkoumal cyklóny, z nichž některé napáchaly velké škody. Tvrdí o nich:</i></p> Cyklóny se sebemenší trochou sněhu dělají strašnou paseku."}}],
[["it27-s-g-psi", 27], aj, {s: {html: "<p><i>Kontext: Karel se zajímá o cyklóny, což jsou obvykle sněhové vánice. Tvrdí o nich:</i></p> Cyklóna se sebemenší trochou sněhu dělá strašnou paseku."}}],
[["it27-s-e-psi", 27], aj, {s: {html: "<p><i>Kontext: Karel zkoumal cyklóny, z nichž některé napáchaly velké škody. Tvrdí o nich:</i></p> Cyklóna se sebemenší trochou sněhu dělá strašnou paseku."}}],

[["it28-pl-g-nopsi", 28], aj, {s: {html: "<p><i>Kontext: Rita se zajímá o kuřačky, což jsou obvykle neduživé ženy. Tvrdí o nich:</i></p> Kuřačky s velkou měrou nemoci jedí přesolenou polévku."}}],
[["it28-pl-e-nopsi", 28], aj, {s: {html: "<p><i>Kontext: Rita zkoumala kuřačky, z nichž některé necítily chuť jídla. Tvrdí o nich:</i></p> Kuřačky s velkou měrou nemoci jedí přesolenou polévku."}}],
[["it28-s-g-nopsi", 28], aj, {s: {html: "<p><i>Kontext: Rita se zajímá o kuřačky, což jsou obvykle neduživé ženy. Tvrdí o nich:</i></p> Kuřačka s velkou měrou nemoci jí přesolenou polévku."}}],
[["it28-s-e-nopsi", 28], aj, {s: {html: "<p><i>Kontext: Rita zkoumala kuřačky, z nichž některé necítily chuť jídla. Tvrdí o nich:</i></p> Kuřačka s velkou měrou nemoci jí přesolenou polévku."}}],
[["it28-pl-g-psi", 28], aj, {s: {html: "<p><i>Kontext: Rita se zajímá o kuřačky, což jsou obvykle neduživé ženy. Tvrdí o nich:</i></p> Kuřačky se sebemenší známkou nemoci jedí přesolenou polévku."}}],
[["it28-pl-e-psi", 28], aj, {s: {html: "<p><i>Kontext: Rita zkoumala kuřačky, z nichž některé necítily chuť jídla. Tvrdí o nich:</i></p> Kuřačky se sebemenší známkou nemoci jedí přesolenou polévku."}}],
[["it28-s-g-psi", 28], aj, {s: {html: "<p><i>Kontext: Rita se zajímá o kuřačky, což jsou obvykle neduživé ženy. Tvrdí o nich:</i></p> Kuřačka se sebemenší známkou nemoci jí přesolenou polévku."}}],
[["it28-s-e-psi", 28], aj, {s: {html: "<p><i>Kontext: Rita zkoumala kuřačky, z nichž některé necítily chuť jídla. Tvrdí o nich:</i></p> Kuřačka se sebemenší známkou nemoci jí přesolenou polévku."}}],			      

[["it29-pl-g-nopsi", 29], aj, {s: {html: "<p><i>Kontext:  Čeněk se zajímá o straky, což jsou obvykle všeteční ptáci. Tvrdí o nich:</i></p> Straky s velkou měrou zvědavosti nosí drobný odpad."}}],
[["it29-pl-e-nopsi", 29], aj, {s: {html: "<p><i>Kontext: Čeněk pozoroval straky, z nichž některé ukradly kousky kovošrotu. Tvrdí o nich:</i></p> Straky s velkou měrou zvědavosti nosí drobný odpad."}}],
[["it29-s-g-nopsi", 29], aj, {s: {html: "<p><i>Kontext: Čeněk se zajímá o straky, což jsou obvykle všeteční ptáci. Tvrdí o nich:</i></p> Straka s velkou měrou zvědavosti nosí drobný odpad."}}],
[["it29-s-e-nopsi", 29], aj, {s: {html: "<p><i>Kontext: Čeněk pozoroval straky, z nichž některé ukradly kousky kovošrotu. Tvrdí o nich:</i></p> Straka s velkou měrou zvědavosti nosí drobný odpad."}}],
[["it29-pl-g-psi", 29], aj, {s: {html: "<p><i>Kontext: Čeněk se zajímá o straky, což jsou obvykle všeteční ptáci. Tvrdí o nich:</i></p> Straky se sebemenší trochou zvědavosti nosí drobný odpad."}}],
[["it29-pl-e-psi", 29], aj, {s: {html: "<p><i>Kontext: Čeněk pozoroval straky, z nichž některé ukradly kousky kovošrotu. Tvrdí o nich:</i></p> Straky se sebemenší trochou zvědavosti nosí drobný odpad."}}],
[["it29-s-g-psi", 29], aj, {s: {html: "<p><i>Kontext: Čeněk se zajímá o straky, což jsou obvykle všeteční ptáci. Tvrdí o nich:</i></p> Straka se sebemenší trochou zvědavosti nosí drobný odpad."}}],
[["it29-s-e-psi", 29], aj, {s: {html: "<p><i>Kontext: Čeněk pozoroval straky, z nichž některé ukradly kousky kovošrotu. Tvrdí o nich:</i></p> Straka se sebemenší trochou zvědavosti nosí drobný odpad."}}],	

[["it30-pl-g-nopsi", 30], aj, {s: {html: "<p><i>Kontext: Mína se zajímá o závodníky, což jsou obvykle nekonvenční povahy. Tvrdí o nich:</i></p> Závodníci s velkou měrou originality jezdí automobilovou rallye."}}],
[["it30-pl-e-nopsi", 30], aj, {s: {html: "<p><i>Kontext: Mína sledovala závodníky, z nichž někteří dokončili silniční závod. Tvrdí o nich:</i></p> Závodníci s velkou měrou originality jezdí automobilovou rallye."}}],
[["it30-s-g-nopsi", 30], aj, {s: {html: "<p><i>Kontext: Mína se zajímá o závodníky, což jsou obvykle nekonvenční povahy. Tvrdí o nich:</i></p> Závodník s velkou měrou originality jezdí automobilovou rallye."}}],
[["it30-s-e-nopsi", 30], aj, {s: {html: "<p><i>Kontext: Mína sledovala závodníky, z nichž někteří dokončili silniční závod. Tvrdí o nich:</i></p> Závodník s velkou měrou originality jezdí automobilovou rallye."}}],
[["it30-pl-g-psi", 30], aj, {s: {html: "<p><i>Kontext: Mína se zajímá o závodníky, což jsou obvykle nekonvenční povahy. Tvrdí o nich:</i></p> Závodníci se sebemenší známkou originality jezdí automobilovou rallye."}}],
[["it30-pl-e-psi", 30], aj, {s: {html: "<p><i>Kontext: Mína sledovala závodníky, z nichž někteří dokončili silniční závod. Tvrdí o nich:</i></p> Závodníci se sebemenší známkou originality jezdí automobilovou rallye."}}],
[["it30-s-g-psi", 30], aj, {s: {html: "<p><i>Kontext: Mína se zajímá o závodníky, což jsou obvykle nekonvenční povahy. Tvrdí o nich:</i></p> Závodník se sebemenší známkou originality jezdí automobilovou rallye."}}],
[["it30-s-e-psi", 30], aj, {s: {html: "<p><i>Kontext: Mína sledovala závodníky, z nichž někteří dokončili silniční závod. Tvrdí o nich:</i></p> Závodník se sebemenší známkou originality jezdí automobilovou rallye."}}],

[["it31-pl-g-nopsi", 31], aj, {s: {html: "<p><i>Kontext: Eva se zajímá o arestantky, což jsou obvykle kajícné pachatelky. Tvrdí o nich:</i></p> Arestantky s vysokou úrovní kázně slyší ptačí zpěv."}}],
[["it31-pl-e-nopsi", 31], aj, {s: {html: "<p><i>Kontext: Eva vyzpovídala arestantky, z nichž některé navštívily venkovní areál. Tvrdí o nich:</i></p> Arestantky s vysokou úrovní kázně slyší ptačí zpěv."}}],
[["it31-s-g-nopsi", 31], aj, {s: {html: "<p><i>Kontext: Eva se zajímá o arestantky, což jsou obvykle kajícné pachatelky. Tvrdí o nich:</i></p> Arestantka s vysokou úrovní kázně slyší ptačí zpěv."}}],
[["it31-s-e-nopsi", 31], aj, {s: {html: "<p><i>Kontext: Eva vyzpovídala arestantky, z nichž některé navštívily venkovní areál. Tvrdí o nich:</i></p> Arestantka s vysokou úrovní kázně slyší ptačí zpěv."}}],
[["it31-pl-g-psi", 31], aj, {s: {html: "<p><i>Kontext: Eva se zajímá o arestantky, což jsou obvykle kajícné pachatelky. Tvrdí o nich:</i></p> Arestantky se sebemenší trochou kázně slyší ptačí zpěv."}}],
[["it31-pl-e-psi", 31], aj, {s: {html: "<p><i>Kontext: Eva vyzpovídala arestantky, z nichž některé navštívily venkovní areál. Tvrdí o nich:</i></p> Arestantky se sebemenší trochou kázně slyší ptačí zpěv."}}],
[["it31-s-g-psi", 31], aj, {s: {html: "<p><i>Kontext: Eva se zajímá o arestantky, což jsou obvykle kajícné pachatelky. Tvrdí o nich:</i></p> Arestantka se sebemenší trochou kázně slyší ptačí zpěv."}}],
[["it31-s-e-psi", 31], aj, {s: {html: "<p><i>Kontext: Eva vyzpovídala arestantky, z nichž některé navštívily venkovní areál. Tvrdí o nich:</i></p> Arestantka se sebemenší trochou kázně slyší ptačí zpěv."}}],

[["it32-pl-g-nopsi", 32], aj, {s: {html: "<p><i>Kontext: Erik se zajímá o seniorky, což jsou obvykle učenlivé ženy. Tvrdí o nich:</i></p> Seniorky s velkou měrou zvídavosti čtou naučnou literaturu."}}],
[["it32-pl-e-nopsi", 32], aj, {s: {html: "<p><i>Kontext: Erik vyzpovídal seniorky, z nichž některé odložily odborné knihy. Tvrdí o nich:</i></p> Seniorky s velkou měrou zvídavosti čtou naučnou literaturu."}}],
[["it32-s-g-nopsi", 32], aj, {s: {html: "<p><i>Kontext: Erik se zajímá o seniorky, což jsou obvykle učenlivé ženy. Tvrdí o nich:</i></p> Seniorka s velkou měrou zvídavosti čte naučnou literaturu."}}],
[["it32-s-e-nopsi", 32], aj, {s: {html: "<p><i>Kontext: Erik vyzpovídal seniorky, z nichž některé odložily odborné knihy. Tvrdí o nich:</i></p> Seniorka s velkou měrou zvídavosti čte naučnou literaturu."}}],
[["it32-pl-g-psi", 32], aj, {s: {html: "<p><i>Kontext: Erik se zajímá o seniorky, což jsou obvykle učenlivé ženy. Tvrdí o nich:</i></p> Seniorky se sebemenší známkou zvídavosti čtou naučnou literaturu."}}],
[["it32-pl-e-psi", 32], aj, {s: {html: "<p><i>Kontext: Erik vyzpovídal seniorky, z nichž některé odložily odborné knihy. Tvrdí o nich:</i></p> Seniorky se sebemenší známkou zvídavosti čtou naučnou literaturu."}}],
[["it32-s-g-psi", 32], aj, {s: {html: "<p><i>Kontext: Erik se zajímá o seniorky, což jsou obvykle učenlivé ženy. Tvrdí o nich:</i></p> Seniorka se sebemenší známkou zvídavosti čte naučnou literaturu."}}],
[["it32-s-e-psi", 32], aj, {s: {html: "<p><i>Kontext: Erik vyzpovídal seniorky, z nichž některé odložily odborné knihy. Tvrdí o nich:</i></p> Seniorka se sebemenší známkou zvídavosti čte naučnou literaturu."}}],
    
["fgood1", aj, {s: {html: "<p><i>Kontext: Jarda pozoroval několik energických koní. Tvrdí o nich:</i></p> Ani jeden velmi energický kůň neuběhl velkou vzdálenost." }}],
["fgood2", aj, {s: {html: "<p><i>Kontext: Jarka zkoumala několik vnímavých zvířat. Tvrdí o nich:</i></p> Ani jedno velmi vnímavé zvíře neuslyšelo velký rámus." }}],
["fgood3", aj, {s: {html: "<p><i>Kontext: Zdeněk vyzpovídal několik zbožných muslimů. Tvrdí o nich:</i></p> Ani jeden velmi zbožný muslim neušel tradiční pouť." }}],
["fgood4", aj, {s: {html: "<p><i>Kontext: Magda sledovala několik arogantních autorů. Tvrdí o nich:</i></p> Ani jeden velmi arogantní autor nenapsal naprostý brak." }}],
["fgood5", aj, {s: {html: "<p><i>Kontext: Jana pozorovala několik štíhlých děvčat. Tvrdí o nich:</i></p> Ani jedno velmi štíhlé děvče nesnědlo hnusné jídlo." }}],
["fgood6", aj, {s: {html: "<p><i>Kontext: Kuba zkoumal několik hrdých koček. Tvrdí o nich:</i></p> Ani jedna velmi hrdá kočka neudělala velký nepořádek." }}],
["fgood7", aj, {s: {html: "<p><i>Kontext: Darek sledoval několik zdatných mul. Tvrdí o nich:</i></p> Ani jedna velmi zdatná mula neodnesla těžký náklad." }}],
["fgood8", aj, {s: {html: "<p><i>Kontext: Jiřka vyzpovídala několik nadaných jasnovidek. Tvrdí o nich:</i></p> Ani jedna velmi nadaná jasnovidka neuviděla smutnou budoucnost." }}],
["fbad9", aj, {s: {html: "<p><i>Kontext: Zdena pozorovala několik mlsných dětí. Tvrdí o nich:</i></p> Ani jedno velmi mlsné dítě snědlo prošlé cukroví." }}],
["fbad10", aj, {s: {html: "<p><i>Kontext: David vyzpovídal několik náročných kritiků. Tvrdí o nich:</i></p> Ani jeden velmi náročný kritik uslyšel špatnou hudbu." }}],
["fbad11", aj, {s: {html: "<p><i>Kontext: Lenka zkoumala několik citlivých žen. Tvrdí o nich:</i></p> Ani jedna velmi citlivá žena napsala dojemnou poezii." }}],
["fbad12", aj, {s: {html: "<p><i>Kontext: Hanka sledovala několik agresivních ohařů. Tvrdí o nich:</i></p> Ani jeden velmi agresivní ohař přinesl zabitou kořist." }}],
["fbad13", aj, {s: {html: "<p><i>Kontext: Pavel pozoroval několik zkušených lyžařek. Tvrdí o nich:</i></p>Ani jedna velmi zkušená lyžařka zajela dobrý slalom." }}],
["fbad14", aj, {s: {html: "<p><i>Kontext: Marek sledoval několik talentovaných hereček. Tvrdí o nich:</i></p> Ani jedna velmi talentovaná herečka sehrála působivé drama." }}],
["fbad15", aj, {s: {html: "<p><i>Kontext: Zora zkoumala několik snaživých vědců. Tvrdí o nich:</i></p> Ani jeden velmi snaživý vědec udělal kvalitní práci." }}],
["fbad16", aj, {s: {html: "<p><i>Kontext: Pepa pozoroval několik disciplinovaných běžců. Tvrdí o nich:</i></p> Ani jeden velmi disciplinovaný běžec zaběhl dobrý maraton." }}],

["fgood17", aj, {s: {html: "<p><i>Kontext: Blanka pozorovala několik ambiciózních šprtů. Tvrdí o nich:</i></p> Ani jeden velmi ambiciózní šprt nedohrál trojrozměrné šachy." }}],
["fgood18", aj, {s: {html: "<p><i>Kontext: Jenda zkoumal několik líných středoškoláků. Tvrdí o nich:</i></p> Ani jeden velmi líný středoškolák nepřinesl špatné vysvědčení." }}],
["fgood19", aj, {s: {html: "<p><i>Kontext: Květa vyzpovídala několik všímavých hlídačů. Tvrdí o nich:</i></p> Ani jeden velmi všímavý hlídač neuviděl podezřelou činnost." }}],
["fgood20", aj, {s: {html: "<p><i>Kontext: Tonda pozoroval několik inteligentních krys. Tvrdí o nich:</i></p> Ani jedna velmi inteligentní krysa nesnědla čerstvou potravu." }}],
["fgood21", aj, {s: {html: "<p><i>Kontext: Evžen sledoval několik individualistických političek. Tvrdí o nich:</i></p> Ani jedna velmi individualistická politička neuslyšela hloupé řeči." }}],
["fgood22", aj, {s: {html: "<p><i>Kontext: Nora pozorovala několik zručných švadlen. Tvrdí o nich:</i></p> Ani jedna velmi zručná švadlena neudělala hodnotné zboží." }}],
["fgood23", aj, {s: {html: "<p><i>Kontext: Cyril sledoval několik činorodých trekařů. Tvrdí o nich:</i></p> Ani jeden velmi činorodý trekař neušel týdenní přechod." }}],
["fgood24", aj, {s: {html: "<p><i>Kontext: Marie vyzpovídala několik vynalézavých saxofonistek. Tvrdí o nich:</i></p> Ani jedna velmi vynalézavá saxofonistka nezahrála jazzovou improvizaci." }}],
["fbad25", aj, {s: {html: "<p><i>Kontext: Bětka sledovala několik odvážných kajakářů. Tvrdí o nich:</i></p> Ani jeden velmi odvážný kajakář sjel divokou vodu." }}],
["fbad26", aj, {s: {html: "<p><i>Kontext: Emil zkoumal několik vášnivých skladatelů. Tvrdí o nich:</i></p> Ani jeden velmi vášnivý skladatel napsal velkolepou operu." }}],
["fbad27", aj, {s: {html: "<p><i>Kontext: Karel zkoumal několik sněhových cyklón. Tvrdí o nich:</i></p> Ani jedna velmi sněhová cyklóna nadělala strašnou paseku." }}],
["fbad28", aj, {s: {html: "<p><i>Kontext: Rita zkoumala několik nemocných kuřaček. Tvrdí o nich:</i></p> Ani jedna velmi nemocná kuřačka snědla přesolenou polévku." }}],
["fbad29", aj, {s: {html: "<p><i>Kontext: Čeněk pozoroval několik zvědavých strak. Tvrdí o nich:</i></p> Ani jedna velmi zvědavá straka odnesla drobný odpad." }}],
["fbad30", aj, {s: {html: "<p><i>Kontext: Eva sledovala několik ukázněných arestantek. Tvrdí o nich:</i></p> Ani jedna velmi ukázněná arestantka uslyšela ptačí zpěv." }}],
["fbad31", aj, {s: {html: "<p><i>Kontext: Erik vyzpovídal několik zvídavých seniorek. Tvrdí o nich:</i></p> Ani jedna velmi zvídavá seniorka dočetla naučnou literaturu." }}],
["fbad32", aj, {s: {html: "<p><i>Kontext: Mína sledovala několik originálních závodníků. Tvrdí o nich:</i></p> Ani jeden velmi originální závodník ujel automobilovou rallye." }}],
			    
];
